// src/lib/dummy-data.ts
import { StudentBooking } from "@/types/booking";

export const bookings: StudentBooking[] = [
  {
    id: "1",
    bookingId: "BK-1001",
    email: "jane.doe@example.com",
    firstName: "Jane",
    lastName: "Doe",
    gender: "female",
    level: "200",
    school: "KNUST",
    studentId: "KNUST12345",
    phone: "0244123456",
    admissionLetterName: "admission-jane.pdf",
    hostelName: "Maple Hostel",
    roomTitle: "One-in-one",
    price: "400",
    emergencyContactName: "John Doe",
    emergencyContactNumber: "0201234567",
    relation: "Father",
    hasMedicalCondition: false,
    status: "pending payment",
    date: "2025-11-10"
  },
  {
    id: "2",
    bookingId: "BK-1002",
    email: "paul.owusu@example.com",
    firstName: "Paul",
    lastName: "Owusu",
    gender: "male",
    level: "300",
    school: "KNUST",
    studentId: "KNUST9876",
    phone: "0244123499",
    admissionLetterName: "admission-paul.pdf",
    hostelName: "Oak Residence",
    roomTitle: "Two-in-two",
    price: "250",
    emergencyContactName: "Ama Owusu",
    emergencyContactNumber: "0244000000",
    relation: "Mother",
    hasMedicalCondition: true,
    medicalCondition: "Asthma",
    status: "pending approval",
    date: "2025-11-02"
  },
  // Example allocated member (approved)
  {
    id: "3",
    bookingId: "BK-1003",
    email: "alex.mensah@example.com",
    firstName: "Alex",
    lastName: "Mensah",
    gender: "male",
    level: "400",
    school: "KNUST",
    studentId: "KNUST54321",
    phone: "0244123000",
    admissionLetterName: "admission-alex.pdf",
    hostelName: "Maple Hostel",
    roomTitle: "Two-in-two",
    price: "300",
    emergencyContactName: "Nana Mensah",
    emergencyContactNumber: "0209988776",
    relation: "Mother",
    hasMedicalCondition: false,
    status: "approved",
    allocatedRoomNumber: 5,
    date: "2025-10-21"
  }
  ,
  // Pre-seeded member (completed onboarding)
  {
    id: "4",
    bookingId: "BK-1004",
    email: "maria.adebayo@example.com",
    firstName: "Maria",
    lastName: "Adebayo",
    gender: "female",
    level: "300",
    school: "KNUST",
    studentId: "KNUST77777",
    phone: "0244123111",
    admissionLetterName: "admission-maria.pdf",
    hostelName: "Oak Residence",
    roomTitle: "Two-in-two",
    price: "300",
    emergencyContactName: "Segun Adebayo",
    emergencyContactNumber: "0201111222",
    relation: "Brother",
    hasMedicalCondition: false,
    status: "approved",
    allocatedRoomNumber: 12,
    date: "2025-09-15"
  },
  // Additional sample bookings for better analytics
  {
    id: "5",
    bookingId: "BK-1005",
    email: "kwame.asante@example.com",
    firstName: "Kwame",
    lastName: "Asante",
    gender: "male",
    level: "100",
    school: "KNUST",
    studentId: "KNUST11111",
    phone: "0244567890",
    admissionLetterName: "admission-kwame.pdf",
    hostelName: "Maple Hostel",
    roomTitle: "Two-in-two",
    price: "280",
    emergencyContactName: "Kofi Asante",
    emergencyContactNumber: "0209876543",
    relation: "Father",
    hasMedicalCondition: false,
    status: "approved",
    allocatedRoomNumber: 8,
    date: "2025-11-15"
  },
  {
    id: "6",
    bookingId: "BK-1006",
    email: "ama.boateng@example.com",
    firstName: "Ama",
    lastName: "Boateng",
    gender: "female",
    level: "200",
    school: "KNUST",
    studentId: "KNUST22222",
    phone: "0244321098",
    admissionLetterName: "admission-ama.pdf",
    hostelName: "Oak Residence",
    roomTitle: "One-in-one",
    price: "450",
    emergencyContactName: "Abena Boateng",
    emergencyContactNumber: "0201234321",
    relation: "Mother",
    hasMedicalCondition: false,
    status: "pending payment",
    date: "2025-11-20"
  },
  {
    id: "7",
    bookingId: "BK-1007",
    email: "kofi.mensah@example.com",
    firstName: "Kofi",
    lastName: "Mensah",
    gender: "male",
    level: "300",
    school: "KNUST",
    studentId: "KNUST33333",
    phone: "0244654321",
    admissionLetterName: "admission-kofi.pdf",
    hostelName: "Maple Hostel",
    roomTitle: "Two-in-two",
    price: "290",
    emergencyContactName: "Akua Mensah",
    emergencyContactNumber: "0209988123",
    relation: "Sister",
    hasMedicalCondition: true,
    medicalCondition: "Diabetes",
    status: "approved",
    allocatedRoomNumber: 15,
    date: "2025-11-08"
  },
  {
    id: "8",
    bookingId: "BK-1008",
    email: "abena.osei@example.com",
    firstName: "Abena",
    lastName: "Osei",
    gender: "female",
    level: "400",
    school: "KNUST",
    studentId: "KNUST44444",
    phone: "0244789012",
    admissionLetterName: "admission-abena.pdf",
    hostelName: "Oak Residence",
    roomTitle: "Two-in-two",
    price: "310",
    emergencyContactName: "Yaw Osei",
    emergencyContactNumber: "0201122334",
    relation: "Father",
    hasMedicalCondition: false,
    status: "pending approval",
    date: "2025-11-18"
  },
  {
    id: "9",
    bookingId: "BK-1009",
    email: "kwesi.adom@example.com",
    firstName: "Kwesi",
    lastName: "Adom",
    gender: "male",
    level: "100",
    school: "KNUST",
    studentId: "KNUST55555",
    phone: "0244890123",
    admissionLetterName: "admission-kwesi.pdf",
    hostelName: "Maple Hostel",
    roomTitle: "One-in-one",
    price: "420",
    emergencyContactName: "Esi Adom",
    emergencyContactNumber: "0209876000",
    relation: "Mother",
    hasMedicalCondition: false,
    status: "approved",
    allocatedRoomNumber: 3,
    date: "2025-11-12"
  },
  {
    id: "10",
    bookingId: "BK-1010",
    email: "akosua.frimpong@example.com",
    firstName: "Akosua",
    lastName: "Frimpong",
    gender: "female",
    level: "200",
    school: "KNUST",
    studentId: "KNUST66666",
    phone: "0244901234",
    admissionLetterName: "admission-akosua.pdf",
    hostelName: "Oak Residence",
    roomTitle: "Two-in-two",
    price: "295",
    emergencyContactName: "Kwame Frimpong",
    emergencyContactNumber: "0201111999",
    relation: "Brother",
    hasMedicalCondition: false,
    status: "approved",
    allocatedRoomNumber: 20,
    date: "2025-11-05"
  },
  {
    id: "11",
    bookingId: "BK-1011",
    email: "yaw.oppong@example.com",
    firstName: "Yaw",
    lastName: "Oppong",
    gender: "male",
    level: "300",
    school: "KNUST",
    studentId: "KNUST77778",
    phone: "0244012345",
    admissionLetterName: "admission-yaw.pdf",
    hostelName: "Maple Hostel",
    roomTitle: "Two-in-two",
    price: "285",
    emergencyContactName: "Ama Oppong",
    emergencyContactNumber: "0209999888",
    relation: "Mother",
    hasMedicalCondition: false,
    status: "pending payment",
    date: "2025-11-22"
  },
  {
    id: "12",
    bookingId: "BK-1012",
    email: "esi.gyasi@example.com",
    firstName: "Esi",
    lastName: "Gyasi",
    gender: "female",
    level: "100",
    school: "KNUST",
    studentId: "KNUST88888",
    phone: "0244123890",
    admissionLetterName: "admission-esi.pdf",
    hostelName: "Oak Residence",
    roomTitle: "One-in-one",
    price: "440",
    emergencyContactName: "Kojo Gyasi",
    emergencyContactNumber: "0201234888",
    relation: "Father",
    hasMedicalCondition: false,
    status: "pending approval",
    date: "2025-11-25"
  }
];

// explicit initial members (bookings that have completed onboarding)
export const initialMembers: StudentBooking[] = [
  // Maria Adebayo (BK-1004) is a completed member
  bookings.find((b) => b.bookingId === "BK-1004") as StudentBooking,
];
